/**
 * UI chrome strings for the broadsheet shell. Story prose comes from translated
 * Markdown; this dictionary covers masthead, deck, stamps, story chrome, and footer.
 *
 * Generated by scripts/gen-ui-i18n.py — edit scripts/ui-i18n-overlays.json then re-run.
 */
import { DEFAULT_LANG, isLang, type Lang } from "./i18n";

export type UiKey =
  | "nav.front"
  | "nav.archive"
  | "nav.method"
  | "nav.sections"
  | "nav.footer"
  | "masthead.est"
  | "masthead.factline"
  | "masthead.motto"
  | "masthead.brandAria"
  | "notice.stamp"
  | "notice.ask"
  | "notice.jump"
  | "lang.label"
  | "lang.aria"
  | "deck.title"
  | "deck.more"
  | "deck.ordered"
  | "deck.restAria"
  | "empty.noStories"
  | "empty.browseArchive"
  | "carousel.aria"
  | "carousel.lead"
  | "carousel.featured"
  | "carousel.continue"
  | "carousel.prev"
  | "carousel.next"
  | "carousel.pause"
  | "carousel.resume"
  | "carousel.select"
  | "teaser.read"
  | "briefs.title"
  | "briefs.aria"
  | "mode.report"
  | "mode.debate"
  | "mode.reportTitle"
  | "mode.debateTitle"
  | "sources.one"
  | "sources.many"
  | "claims.one"
  | "claims.many"
  | "verified"
  | "story.of"
  | "section.context"
  | "section.report"
  | "section.debate"
  | "section.grounded"
  | "section.whatWeKnow"
  | "section.photos"
  | "section.cited"
  | "nav.prev"
  | "nav.next"
  | "nav.backEdition"
  | "nav.storyAria"
  | "debate.bottomLine"
  | "debate.oneAccount"
  | "debate.otherAccount"
  | "debate.empty"
  | "claim.primary"
  | "impact.high"
  | "impact.notable"
  | "impact.moderate"
  | "impact.routine"
  | "impact.title"
  | "footer.correspondence"
  | "footer.lettersHeadline"
  | "footer.lettersLede"
  | "footer.lettersCta"
  | "footer.lettersNote"
  | "footer.tagline"
  | "footer.audit"
  | "footer.service"
  | "footer.feedbackAria"
  | "home.backIssues";

type Dict = Record<UiKey, string>;

const en: Dict = {
  "nav.front": "Front Page",
  "nav.archive": "Archive",
  "nav.method": "Method",
  "nav.sections": "Sections",
  "nav.footer": "Footer",
  "masthead.est": "Est. MMXXVI",
  "masthead.factline": "Fact-grounded · Auditable",
  "masthead.motto": "Someone has to keep you grounded.",
  "masthead.brandAria": "The Grounded Times — front page",
  "notice.stamp": "Notice",
  "notice.ask": "Have we kept you grounded?",
  "notice.jump": "Tell us ↓",
  "lang.label": "Language",
  "lang.aria": "Language",
  "deck.title": "In this edition",
  "deck.more": "{n} more dispatches",
  "deck.ordered": "ordered by importance",
  "deck.restAria": "The rest of this edition",
  "empty.noStories": "No stories were grounded in this edition.",
  "empty.browseArchive": "Browse the back issues →",
  "carousel.aria": "Featured dispatches",
  "carousel.lead": "The lead — by importance",
  "carousel.featured": "Featured — by importance",
  "carousel.continue": "Continue reading →",
  "carousel.prev": "Previous featured story",
  "carousel.next": "Next featured story",
  "carousel.pause": "Pause auto-rotation",
  "carousel.resume": "Resume auto-rotation",
  "carousel.select": "Select a featured story",
  "teaser.read": "Read",
  "briefs.title": "In Brief",
  "briefs.aria": "News in brief",
  "mode.report": "Report",
  "mode.debate": "Debate",
  "mode.reportTitle": "Report — grounded in a primary/official source.",
  "mode.debateTitle": "Contested — no primary or official source; presented as a two-sided debate.",
  "sources.one": "1 source",
  "sources.many": "{n} sources",
  "claims.one": "1 claim kept",
  "claims.many": "{n} claims kept",
  "verified": "{n} verified",
  "story.of": "No. {n} of {total}",
  "section.context": "Context",
  "section.report": "Report",
  "section.debate": "The debate",
  "section.grounded": "Grounded points",
  "section.whatWeKnow": "What we know",
  "section.photos": "Photographs",
  "section.cited": "Cited sources",
  "nav.prev": "← Previous",
  "nav.next": "Next →",
  "nav.backEdition": "Back to the edition",
  "nav.storyAria": "Story navigation",
  "debate.bottomLine": "The bottom line",
  "debate.oneAccount": "One account",
  "debate.otherAccount": "The other account",
  "debate.empty": "No counter-argument could be constructed from the sources.",
  "claim.primary": "Primary",
  "impact.high": "High",
  "impact.notable": "Notable",
  "impact.moderate": "Moderate",
  "impact.routine": "Routine",
  "impact.title": "Importance: {label}",
  "footer.correspondence": "Correspondence",
  "footer.lettersHeadline": "Have we kept you grounded?",
  "footer.lettersLede": "The paper is written by machine; the verdict is yours. Tell us what landed, what felt off, and whether the citations earned your trust — a minute of frankness beats a thousand polite nods.",
  "footer.lettersCta": "Write to the editor →",
  "footer.lettersNote": "Anonymous · takes about a minute · we actually read these",
  "footer.tagline": "Every claim, a citation",
  "footer.audit": "Every claim above was extracted from source material, verified against its citations, and audited for hallucination. Items marked DEBATE lack a primary/official source and are presented as contested rather than confirmed.",
  "footer.service": "An autonomous, fact-grounded news service · Published by machine, grounded in sources",
  "footer.feedbackAria": "Reader feedback",
  "home.backIssues": "Read the back-issues →",
};

function overlay(base: Dict, patch: Partial<Dict>): Dict {
  return { ...base, ...patch };
}

const hi = overlay(en, {
  "nav.front": "मुखपृष्ठ",
  "nav.archive": "पुरालेख",
  "nav.method": "विधि",
  "nav.sections": "खंड",
  "nav.footer": "फुटर",
  "masthead.factline": "तथ्यों पर आधारित · जाँच योग्य",
  "masthead.motto": "किसी को तो आपको ग्राउंडेड रखना ही होगा।",
  "masthead.brandAria": "द ग्राउंडेड टाइम्स — मुखपृष्ठ",
  "notice.stamp": "सूचना",
  "notice.ask": "क्या हमने आपको ग्राउंडेड रखा?",
  "notice.jump": "हमें बताएँ ↓",
  "lang.label": "भाषा",
  "lang.aria": "भाषा चुनें",
  "deck.title": "इस संस्करण में",
  "deck.more": "{n} और डिस्पैच",
  "deck.ordered": "महत्व के अनुसार क्रमबद्ध",
  "deck.restAria": "इस संस्करण की शेष खबरें",
  "empty.noStories": "इस संस्करण में कोई स्टोरी ग्राउंडेड नहीं हुई।",
  "empty.browseArchive": "पुराने अंक देखें →",
  "carousel.aria": "प्रमुख डिस्पैच",
  "carousel.lead": "मुख्य खबर — महत्व के अनुसार",
  "carousel.featured": "विशेष — महत्व के अनुसार",
  "carousel.continue": "पढ़ना जारी रखें →",
  "carousel.prev": "पिछली प्रमुख खबर",
  "carousel.next": "अगली प्रमुख खबर",
  "carousel.pause": "स्वतः घुमाव रोकें",
  "carousel.resume": "स्वतः घुमाव फिर शुरू करें",
  "carousel.select": "प्रमुख खबर चुनें",
  "teaser.read": "पढ़ें",
  "briefs.title": "संक्षेप में",
  "briefs.aria": "संक्षिप्त समाचार",
  "mode.report": "रिपोर्ट",
  "mode.debate": "बहस",
  "mode.reportTitle": "रिपोर्ट — प्राथमिक/आधिकारिक स्रोत पर आधारित।",
  "mode.debateTitle": "विवादास्पद — कोई प्राथमिक/आधिकारिक स्रोत नहीं; दो पक्षों की बहस के रूप में प्रस्तुत।",
  "sources.one": "1 स्रोत",
  "sources.many": "{n} स्रोत",
  "claims.one": "1 दावा सुरक्षित",
  "claims.many": "{n} दावे सुरक्षित",
  "verified": "{n} सत्यापित",
  "story.of": "संख्या {n} / {total}",
  "section.context": "संदर्भ",
  "section.report": "रिपोर्ट",
  "section.debate": "बहस",
  "section.grounded": "ग्राउंडेड बिंदु",
  "section.whatWeKnow": "जो हमें पता है",
  "section.photos": "तस्वीरें",
  "section.cited": "उल्लिखित स्रोत",
  "nav.prev": "← पिछला",
  "nav.next": "अगला →",
  "nav.backEdition": "संस्करण पर वापस जाएँ",
  "nav.storyAria": "स्टोरी नेविगेशन",
  "debate.bottomLine": "निष्कर्ष",
  "debate.oneAccount": "एक पक्ष",
  "debate.otherAccount": "दूसरा पक्ष",
  "debate.empty": "स्रोतों से कोई प्रतिपक्ष तर्क नहीं बन सका।",
  "claim.primary": "प्राथमिक",
  "impact.high": "उच्च",
  "impact.notable": "उल्लेखनीय",
  "impact.moderate": "मध्यम",
  "impact.routine": "सामान्य",
  "impact.title": "महत्व: {label}",
  "footer.correspondence": "पत्राचार",
  "footer.lettersHeadline": "क्या हमने आपको ग्राउंडेड रखा?",
  "footer.lettersLede": "अखबार मशीन लिखती है; फैसला आपका है। बताएँ क्या ठीक लगा, क्या नहीं, और क्या उद्धरणों ने आपका भरोसा जीता — एक मिनट की ईमानदारी हज़ार विनम्र सहमतियों से बेहतर है।",
  "footer.lettersCta": "संपादक को लिखें →",
  "footer.lettersNote": "अनाम · लगभग एक मिनट · हम सच में इन्हें पढ़ते हैं",
  "footer.tagline": "हर दावे के साथ उद्धरण",
  "footer.audit": "ऊपर का हर दावा स्रोत सामग्री से निकाला गया, उसके उद्धरणों से जाँचा गया, और भ्रम/हैलुसिनेशन के लिए परखा गया। जिन पर DEBATE/बहस लिखा है, उनमें प्राथमिक/आधिकारिक स्रोत नहीं है और उन्हें विवादास्पद के रूप में प्रस्तुत किया गया है।",
  "footer.service": "एक स्वायत्त, तथ्यों पर आधारित समाचार सेवा · मशीन द्वारा प्रकाशित, स्रोतों पर आधारित",
  "footer.feedbackAria": "पाठक प्रतिक्रिया",
  "home.backIssues": "पुराने अंक पढ़ें →",
});

const kn = overlay(en, {
  "nav.front": "ಮುಖಪುಟ",
  "nav.archive": "ಆರ್ಕೈವ್",
  "nav.method": "ವಿಧಾನ",
  "masthead.factline": "ಸತ್ಯಾಧಾರಿತ · ಪರಿಶೀಲನೀಯ",
  "masthead.motto": "ಯಾರಾದರೂ ನಿಮ್ಮನ್ನು ಗ್ರೌಂಡೆಡ್ ಆಗಿರಿಸಬೇಕು.",
  "notice.stamp": "ಸೂಚನೆ",
  "notice.ask": "ನಾವು ನಿಮ್ಮನ್ನು ಗ್ರೌಂಡೆಡ್ ಆಗಿರಿಸಿದ್ದೇವೆಯೇ?",
  "notice.jump": "ನಮಗೆ ತಿಳಿಸಿ ↓",
  "lang.label": "ಭಾಷೆ",
  "lang.aria": "ಭಾಷೆ ಆಯ್ಕೆ",
  "deck.title": "ಈ ಸಂಚಿಕೆಯಲ್ಲಿ",
  "deck.more": "{n} ಇನ್ನಷ್ಟು ಸುದ್ದಿ",
  "deck.ordered": "ಮಹತ್ವದ ಕ್ರಮದಲ್ಲಿ",
  "teaser.read": "ಓದಿ",
  "briefs.title": "ಸಂಕ್ಷಿಪ್ತವಾಗಿ",
  "mode.report": "ವರದಿ",
  "mode.debate": "ಚರ್ಚೆ",
  "sources.one": "1 ಮೂಲ",
  "sources.many": "{n} ಮೂಲಗಳು",
  "claims.one": "1 ಹೇಳಿಕೆ ಉಳಿಸಲಾಗಿದೆ",
  "claims.many": "{n} ಹೇಳಿಕೆಗಳು ಉಳಿಸಲಾಗಿವೆ",
  "section.context": "ಹಿನ್ನೆಲೆ",
  "section.report": "ವರದಿ",
  "section.debate": "ಚರ್ಚೆ",
  "section.grounded": "ಗ್ರೌಂಡೆಡ್ ಅಂಶಗಳು",
  "section.cited": "ಉಲ್ಲೇಖಿತ ಮೂಲಗಳು",
  "nav.prev": "← ಹಿಂದಿನದು",
  "nav.next": "ಮುಂದಿನದು →",
  "nav.backEdition": "ಸಂಚಿಕೆಗೆ ಹಿಂತಿರುಗಿ",
  "carousel.continue": "ಓದುವುದನ್ನು ಮುಂದುವರಿಸಿ →",
  "footer.correspondence": "ಪತ್ರವ್ಯವಹಾರ",
  "footer.lettersHeadline": "ನಾವು ನಿಮ್ಮನ್ನು ಗ್ರೌಂಡೆಡ್ ಆಗಿರಿಸಿದ್ದೇವೆಯೇ?",
  "footer.lettersCta": "ಸಂಪಾದಕರಿಗೆ ಬರೆಯಿರಿ →",
  "footer.tagline": "ಪ್ರತಿ ಹೇಳಿಕೆಗೂ ಉಲ್ಲೇಖ",
  "home.backIssues": "ಹಿಂದಿನ ಸಂಚಿಕೆಗಳನ್ನು ಓದಿ →",
  "deck.restAria": "ಈ ಸಂಚಿಕೆಯ ಉಳಿದ ಸುದ್ದಿಗಳು",
  "empty.noStories": "ಈ ಸಂಚಿಕೆಯಲ್ಲಿ ಯಾವುದೇ ಸುದ್ದಿ ಗ್ರೌಂಡೆಡ್ ಆಗಿಲ್ಲ.",
  "empty.browseArchive": "ಹಿಂದಿನ ಸಂಚಿಕೆಗಳನ್ನು ನೋಡಿ →",
  "carousel.aria": "ಪ್ರಮುಖ ಸುದ್ದಿಗಳು",
  "carousel.lead": "ಮುಖ್ಯ ಸುದ್ದಿ — ಮಹತ್ವದ ಪ್ರಕಾರ",
  "carousel.featured": "ವಿಶೇಷ — ಮಹತ್ವದ ಪ್ರಕಾರ",
  "carousel.prev": "ಹಿಂದಿನ ಪ್ರಮುಖ ಸುದ್ದಿ",
  "carousel.next": "ಮುಂದಿನ ಪ್ರಮುಖ ಸುದ್ದಿ",
  "carousel.pause": "ಸ್ವಯಂ ತಿರುಗುವಿಕೆ ನಿಲ್ಲಿಸಿ",
  "carousel.resume": "ಸ್ವಯಂ ತಿರುಗುವಿಕೆ ಮುಂದುವರಿಸಿ",
  "carousel.select": "ಪ್ರಮುಖ ಸುದ್ದಿ ಆಯ್ಕೆಮಾಡಿ",
  "briefs.aria": "ಸಂಕ್ಷಿಪ್ತ ಸುದ್ದಿ",
  "mode.reportTitle": "ವರದಿ — ಪ್ರಾಥಮಿಕ/ಅಧಿಕೃತ ಮೂಲದಲ್ಲಿ ನೆಲೆಗೊಂಡಿದೆ.",
  "mode.debateTitle": "ವಿವಾದಾಸ್ಪದ — ಪ್ರಾಥಮಿಕ/ಅಧಿಕೃತ ಮೂಲವಿಲ್ಲ.",
  "verified": "{n} ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
  "story.of": "ಸಂಖ್ಯೆ {n} / {total}",
  "section.whatWeKnow": "ನಮಗೆ ತಿಳಿದಿರುವುದು",
  "section.photos": "ಛಾಯಾಚಿತ್ರಗಳು",
  "nav.storyAria": "ಸುದ್ದಿ ನ್ಯಾವಿಗೇಷನ್",
  "debate.bottomLine": "ತೀರ್ಮಾನ",
  "debate.oneAccount": "ಒಂದು ಪಕ್ಷ",
  "debate.otherAccount": "ಇನ್ನೊಂದು ಪಕ್ಷ",
  "debate.empty": "ಮೂಲಗಳಿಂದ ಪ್ರತಿಪಕ್ಷ ವಾದ ನಿರ್ಮಿಸಲಾಗಲಿಲ್ಲ.",
  "claim.primary": "ಪ್ರಾಥಮಿಕ",
  "impact.high": "ಹೆಚ್ಚು",
  "impact.notable": "ಗಮನಾರ್ಹ",
  "impact.moderate": "ಮಧ್ಯಮ",
  "impact.routine": "ಸಾಮಾನ್ಯ",
  "impact.title": "ಮಹತ್ವ: {label}",
  "footer.lettersLede": "ಪತ್ರಿಕೆಯನ್ನು ಯಂತ್ರ ಬರೆಯುತ್ತದೆ; ತೀರ್ಪು ನಿಮ್ಮದು.",
  "footer.lettersNote": "ಅನಾಮಧೇಯ · ಸುಮಾರು ಒಂದು ನಿಮಿಷ · ನಾವು ಓದುತ್ತೇವೆ",
  "footer.audit": "ಮೇಲಿನ ಪ್ರತಿ ಹೇಳಿಕೆಯನ್ನು ಮೂಲದಿಂದ ತೆಗೆಯಲಾಗಿದೆ ಮತ್ತು ಪರಿಶೀಲಿಸಲಾಗಿದೆ.",
  "footer.service": "ಸ್ವಯಂಚಾಲಿತ, ಸತ್ಯಾಧಾರಿತ ಸುದ್ದಿ ಸೇವೆ",
  "footer.feedbackAria": "ಓದುಗರ ಪ್ರತಿಕ್ರಿಯೆ",
  "nav.sections": "ವಿಭಾಗಗಳು",
  "nav.footer": "ಫುಟರ್",
  "masthead.brandAria": "ದಿ ಗ್ರೌಂಡೆಡ್ ಟೈಮ್ಸ್ — ಮುಖಪುಟ",
});

const mr = overlay(en, {
  "nav.front": "मुखपृष्ठ",
  "nav.archive": "संग्रह",
  "nav.method": "पद्धत",
  "nav.sections": "खंड",
  "nav.footer": "फुटर",
  "masthead.factline": "तथ्याधारित · तपासणीय",
  "masthead.motto": "कोणीतरी तुम्हाला ग्राउंडेड ठेवायला हवे.",
  "masthead.brandAria": "द ग्राउंडेड टाइम्स — मुखपृष्ठ",
  "notice.stamp": "सूचना",
  "notice.ask": "आम्ही तुम्हाला ग्राउंडेड ठेवले का?",
  "notice.jump": "आम्हाला सांगा ↓",
  "lang.label": "भाषा",
  "lang.aria": "भाषा निवडा",
  "deck.title": "या अंकात",
  "deck.more": "{n} आणखी बातम्या",
  "deck.ordered": "महत्त्वानुसार क्रम",
  "deck.restAria": "इस संस्करण की शेष खबरें",
  "empty.noStories": "इस संस्करण में कोई स्टोरी ग्राउंडेड नहीं हुई।",
  "empty.browseArchive": "पुराने अंक देखें →",
  "carousel.aria": "प्रमुख डिस्पैच",
  "carousel.lead": "मुख्य खबर — महत्व के अनुसार",
  "carousel.featured": "विशेष — महत्व के अनुसार",
  "carousel.continue": "वाचन सुरू ठेवा →",
  "carousel.prev": "पिछली प्रमुख खबर",
  "carousel.next": "अगली प्रमुख खबर",
  "carousel.pause": "स्वतः घुमाव रोकें",
  "carousel.resume": "स्वतः घुमाव फिर शुरू करें",
  "carousel.select": "प्रमुख खबर चुनें",
  "teaser.read": "वाचा",
  "briefs.title": "थोडक्यात",
  "briefs.aria": "संक्षिप्त समाचार",
  "mode.report": "अहवाल",
  "mode.debate": "चर्चा",
  "mode.reportTitle": "रिपोर्ट — प्राथमिक/आधिकारिक स्रोत पर आधारित।",
  "mode.debateTitle": "विवादास्पद — कोई प्राथमिक/आधिकारिक स्रोत नहीं; दो पक्षों की बहस के रूप में प्रस्तुत।",
  "sources.one": "1 स्रोत",
  "sources.many": "{n} स्रोत",
  "claims.one": "1 दावा सुरक्षित",
  "claims.many": "{n} दावे सुरक्षित",
  "verified": "{n} सत्यापित",
  "story.of": "संख्या {n} / {total}",
  "section.context": "संदर्भ",
  "section.report": "अहवाल",
  "section.debate": "चर्चा",
  "section.grounded": "ग्राउंडेड बिंदु",
  "section.whatWeKnow": "जो हमें पता है",
  "section.photos": "तस्वीरें",
  "section.cited": "उल्लिखित स्रोत",
  "nav.prev": "← मागील",
  "nav.next": "पुढील →",
  "nav.backEdition": "अंकाकडे परत",
  "nav.storyAria": "स्टोरी नेविगेशन",
  "debate.bottomLine": "निष्कर्ष",
  "debate.oneAccount": "एक पक्ष",
  "debate.otherAccount": "दूसरा पक्ष",
  "debate.empty": "स्रोतों से कोई प्रतिपक्ष तर्क नहीं बन सका।",
  "claim.primary": "प्राथमिक",
  "impact.high": "उच्च",
  "impact.notable": "उल्लेखनीय",
  "impact.moderate": "मध्यम",
  "impact.routine": "सामान्य",
  "impact.title": "महत्व: {label}",
  "footer.correspondence": "पत्रव्यवहार",
  "footer.lettersHeadline": "आम्ही तुम्हाला ग्राउंडेड ठेवले का?",
  "footer.lettersLede": "अखबार मशीन लिखती है; फैसला आपका है। बताएँ क्या ठीक लगा, क्या नहीं, और क्या उद्धरणों ने आपका भरोसा जीता — एक मिनट की ईमानदारी हज़ार विनम्र सहमतियों से बेहतर है।",
  "footer.lettersCta": "संपादकांना लिहा →",
  "footer.lettersNote": "अनाम · लगभग एक मिनट · हम सच में इन्हें पढ़ते हैं",
  "footer.tagline": "हर दावे के साथ उद्धरण",
  "footer.audit": "ऊपर का हर दावा स्रोत सामग्री से निकाला गया, उसके उद्धरणों से जाँचा गया, और भ्रम/हैलुसिनेशन के लिए परखा गया। जिन पर DEBATE/बहस लिखा है, उनमें प्राथमिक/आधिकारिक स्रोत नहीं है और उन्हें विवादास्पद के रूप में प्रस्तुत किया गया है।",
  "footer.service": "एक स्वायत्त, तथ्यों पर आधारित समाचार सेवा · मशीन द्वारा प्रकाशित, स्रोतों पर आधारित",
  "footer.feedbackAria": "पाठक प्रतिक्रिया",
  "home.backIssues": "जुने अंक वाचा →",
});

const te = overlay(en, {
  "nav.front": "ముఖపుట",
  "nav.archive": "ఆర్కైవ్",
  "nav.method": "పద్ధతి",
  "masthead.factline": "వాస్తవాధారిత · ధృవీకరించదగినది",
  "masthead.motto": "ఎవరైనా మిమ్మల్ని గ్రౌండెడ్‌గా ఉంచాలి.",
  "notice.stamp": "నోటీసు",
  "notice.ask": "మేము మిమ్మల్ని గ్రౌండెడ్‌గా ఉంచామా?",
  "notice.jump": "మాకు చెప్పండి ↓",
  "lang.label": "భాష",
  "lang.aria": "భాష ఎంపిక",
  "deck.title": "ఈ సంచికలో",
  "deck.more": "{n} మరిన్ని వార్తలు",
  "deck.ordered": "ప్రాముఖ్యత క్రమంలో",
  "teaser.read": "చదవండి",
  "briefs.title": "సంక్షిప్తంగా",
  "mode.report": "రిపోర్ట్",
  "mode.debate": "చర్చ",
  "sources.one": "1 మూలం",
  "sources.many": "{n} మూలాలు",
  "claims.one": "1 వాదన ఉంచబడింది",
  "claims.many": "{n} వాదనలు ఉంచబడ్డాయి",
  "section.context": "నేపథ్యం",
  "section.report": "రిపోర్ట్",
  "section.debate": "చర్చ",
  "section.grounded": "గ్రౌండెడ్ అంశాలు",
  "section.cited": "ఉదహరించిన మూలాలు",
  "nav.prev": "← మునుపటి",
  "nav.next": "తదుపరి →",
  "nav.backEdition": "సంచికకు తిరిగి వెళ్ళండి",
  "carousel.continue": "చదవడం కొనసాగించండి →",
  "footer.correspondence": "ఉత్తరప్రత్యుత్తరాలు",
  "footer.lettersHeadline": "మేము మిమ్మల్ని గ్రౌండెడ్‌గా ఉంచామా?",
  "footer.lettersCta": "ఎడిటర్‌కు రాయండి →",
  "footer.tagline": "ప్రతి వాదనకు ఉల్లేఖనం",
  "home.backIssues": "పాత సంచికలు చదవండి →",
  "deck.restAria": "ఈ సంచికలోని మిగిలిన వార్తలు",
  "empty.noStories": "ఈ సంచికలో ఏ వార్తా గ్రౌండెడ్ కాలేదు.",
  "empty.browseArchive": "పాత సంచికలు చూడండి →",
  "carousel.aria": "ప్రధాన వార్తలు",
  "carousel.lead": "ముఖ్య వార్త — ప్రాముఖ్యత ప్రకారం",
  "carousel.featured": "ప్రత్యేకం — ప్రాముఖ్యత ప్రకారం",
  "carousel.prev": "మునుపటి ప్రధాన వార్త",
  "carousel.next": "తదుపరి ప్రధాన వార్త",
  "carousel.pause": "స్వయంచాలక తిరుగుడు ఆపండి",
  "carousel.resume": "స్వయంచాలక తిరుగుడు కొనసాగించండి",
  "carousel.select": "ప్రధాన వార్తను ఎంచుకోండి",
  "briefs.aria": "సంక్షిప్త వార్తలు",
  "mode.reportTitle": "రిపోర్ట్ — ప్రాథమిక/అధికారిక మూలంపై ఆధారపడి.",
  "mode.debateTitle": "వివాదాస్పదం — ప్రాథమిక/అధికారిక మూలం లేదు.",
  "verified": "{n} ధృవీకరించబడింది",
  "story.of": "సంఖ్య {n} / {total}",
  "section.whatWeKnow": "మనకు తెలిసినవి",
  "section.photos": "ఫోటోలు",
  "nav.storyAria": "వార్తా నావిగేషన్",
  "debate.bottomLine": "ముగింపు",
  "debate.oneAccount": "ఒక వైపు",
  "debate.otherAccount": "మరో వైపు",
  "debate.empty": "మూలాల నుంచి ప్రతిపక్ష వాదన నిర్మించలేకపోయాం.",
  "claim.primary": "ప్రాథమికం",
  "impact.high": "ఎక్కువ",
  "impact.notable": "గమనార్హం",
  "impact.moderate": "మధ్యస్థం",
  "impact.routine": "సాధారణం",
  "impact.title": "ప్రాముఖ్యత: {label}",
  "footer.lettersLede": "పత్రికను యంత్రం రాస్తుంది; తీర్పు మీది.",
  "footer.lettersNote": "అనామకం · సుమారు ఒక నిమిషం · మేము చదువుతాం",
  "footer.audit": "పైన ఉన్న ప్రతి వాదన మూల పదార్థం నుంచి తీయబడింది మరియు ధృవీకరించబడింది.",
  "footer.service": "స్వయంచాలక, వాస్తవాధారిత వార్తా సేవ",
  "footer.feedbackAria": "పాఠకుల అభిప్రాయం",
  "nav.sections": "విభాగాలు",
  "nav.footer": "ఫుటర్",
  "masthead.brandAria": "ద గ్రౌండెడ్ టైమ్స్ — ముఖపుట",
});

const DICTS: Partial<Record<Lang, Dict>> = { en, hi, kn, mr, te };

export function uiLang(value: string | null | undefined): Lang {
  return isLang(value) ? value : DEFAULT_LANG;
}

/** Interpolate `{n}` / `{total}` / `{label}` placeholders. */
export function t(
  lang: string | null | undefined,
  key: UiKey,
  vars?: Record<string, string | number>,
): string {
  const code = uiLang(lang);
  const dict = DICTS[code] ?? en;
  let out = dict[key] ?? en[key] ?? key;
  if (key === "deck.more" && code === "en" && vars?.n !== undefined) {
    const n = Number(vars.n);
    return `${n} more dispatch${n === 1 ? "" : "es"}`;
  }
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      out = out.split(`{${k}}`).join(String(v));
    }
  }
  return out;
}

export function sourceCountLabel(
  lang: string | null | undefined,
  n: number,
): string {
  return n === 1 ? t(lang, "sources.one") : t(lang, "sources.many", { n });
}

export function claimsKeptLabel(
  lang: string | null | undefined,
  n: number,
): string {
  return n === 1 ? t(lang, "claims.one") : t(lang, "claims.many", { n });
}
